package com.haroot.pokebot.tools;
/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/

import org.springframework.stereotype.Component;

import com.github.scribejava.core.model.OAuth2AccessToken;
import com.github.scribejava.core.pkce.PKCE;
import com.github.scribejava.core.pkce.PKCECodeChallengeMethod;
import com.haroot.pokebot.config.ResourcePathConfig;
import com.haroot.pokebot.config.UserInfoConfig;
import com.haroot.pokebot.dto.TokenDto;
import com.haroot.pokebot.utils.MapperUtils;
import com.twitter.clientlib.auth.TwitterOAuth20Service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * 新規AccessToken取得
 *
 * @author haroot
 *
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class OAuth20GetAccessToken {
	private final ResourcePathConfig resourcePathConfig;
	private final UserInfoConfig userInfoConfig;

	/**
	 * 2026/6/1現在、Developer ConsoleのAgentから取得できるため未テスト
	 */
	public String getAuthorizationUrl() {
		PKCE pkce = buildPkce();
		TwitterOAuth20Service service = buildService();
		String url = service.getAuthorizationUrl(pkce, "request-by-haroot8601");
		log.info("Authorization URL: {}", url);
		return url;
	}

	/**
	 * 2026/6/1現在、Developer ConsoleのAgentから取得できるため未テスト
	 */
	public boolean updateToken(String code) {
		TwitterOAuth20Service service = buildService();
		try {
			OAuth2AccessToken accessToken = service.getAccessToken(buildPkce(), code);
			TokenDto tokenDto = new TokenDto();
			tokenDto.setAccessToken(accessToken.getAccessToken());
			tokenDto.setRefreshToken(accessToken.getRefreshToken());
			boolean saved = MapperUtils.writeJson(resourcePathConfig.getToken(), tokenDto);
			if (saved) {
				log.info("token.json updated successfully.");
			} else {
				log.error("Failed to save token.json.");
			}
			return saved;
		} catch (Exception ex) {
			log.error("Error while getting the access token: {}", ex.getMessage(), ex);
			return false;
		}
	}

	/**
	 * 2026/6/1現在、Developer ConsoleのAgentから取得できるため未テスト
	 */
	private TwitterOAuth20Service buildService() {
		return new TwitterOAuth20Service(
				userInfoConfig.getClientId(),
				userInfoConfig.getClientSecret(),
				userInfoConfig.getRedirectUrl(),
				userInfoConfig.getAccessScope());
	}

	/**
	 * 2026/6/1現在、Developer ConsoleのAgentから取得できるため未テスト
	 */
	private PKCE buildPkce() {
		PKCE pkce = new PKCE();
		pkce.setCodeChallenge("challenge");
		pkce.setCodeChallengeMethod(PKCECodeChallengeMethod.PLAIN);
		pkce.setCodeVerifier("challenge");
		return pkce;
	}
}
