package com.haroot.pokebot.others;
/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/

import java.util.Scanner;

import com.github.scribejava.core.model.OAuth2AccessToken;
import com.github.scribejava.core.pkce.PKCE;
import com.github.scribejava.core.pkce.PKCECodeChallengeMethod;
import com.haroot.pokebot.dto.TokenDto;
import com.haroot.pokebot.dto.UserInfoDto;
import com.haroot.pokebot.utils.MapperUtils;
import com.twitter.clientlib.TwitterCredentialsOAuth2;
import com.twitter.clientlib.auth.TwitterOAuth20Service;

/**
 * 新規AccessToken取得(Javaプログラム)
 * 
 * @author sekiharuhito
 *
 */
public class OAuth20GetAccessToken {
	private final static String JSON_PATH = "src/main/resources/static/json";
	private final static String TOKEN_FILE = "/token.json";
	private final static String USER_INFO_FILE = "/userInfo.json";

	public static void main(String[] args) {
		TokenDto tokenDto = MapperUtils.readJson(JSON_PATH + TOKEN_FILE, TokenDto.class);
		UserInfoDto userInfoDto = MapperUtils.readJson(JSON_PATH + USER_INFO_FILE, UserInfoDto.class);
		if (tokenDto == null || userInfoDto == null) {
			return;
		}
		TwitterCredentialsOAuth2 credentials = new TwitterCredentialsOAuth2(userInfoDto.getClientId(),
				userInfoDto.getClientSecret(), tokenDto.getAccessToken(), tokenDto.getRefreshToken());

		OAuth2AccessToken accessToken = getAccessToken(credentials, userInfoDto);
		if (accessToken == null) {
			System.out.println("token is null");
			return;
		}

		// Setting the access & refresh tokens into TwitterCredentialsOAuth2
		credentials.setTwitterOauth2AccessToken(accessToken.getAccessToken());
		credentials.setTwitterOauth2RefreshToken(accessToken.getRefreshToken());
	}

	public static OAuth2AccessToken getAccessToken(TwitterCredentialsOAuth2 credentials, UserInfoDto userInfoDto) {
		final String REDIRECT_URL = userInfoDto.getRedirectUrl();
		final String ACCESS_SCOPE = userInfoDto.getAccessScope();
		TwitterOAuth20Service service = new TwitterOAuth20Service(credentials.getTwitterOauth2ClientId(),
				credentials.getTwitterOAuth2ClientSecret(), REDIRECT_URL, ACCESS_SCOPE);

		OAuth2AccessToken accessToken = null;
		try (final Scanner in = new Scanner(System.in, "UTF-8");) {
			System.out.println("Fetching the Authorization URL...");

			final String secretState = "state";
			PKCE pkce = new PKCE();
			pkce.setCodeChallenge("challenge");
			pkce.setCodeChallengeMethod(PKCECodeChallengeMethod.PLAIN);
			pkce.setCodeVerifier("challenge");
			String authorizationUrl = service.getAuthorizationUrl(pkce, secretState);

			System.out.println("Go to the Authorization URL and authorize your App:\n" + authorizationUrl
					+ "\nAfter that paste the authorization code here\n>>");
			final String code = in.nextLine();
			System.out.println("\nTrading the Authorization Code for an Access Token...");
			accessToken = service.getAccessToken(pkce, code);

			System.out.println("Access token: " + accessToken.getAccessToken());
			System.out.println("Refresh token: " + accessToken.getRefreshToken());
		} catch (

		Exception e) {
			System.err.println("Error while getting the access token:\n " + e);
			e.printStackTrace();
		}
		return accessToken;
	}
}
